name: C++
on: [push]
jobs:
  check-bats-version:
    runs-on: windows-latest
    steps:
      - name: artifact output
        run: |
         bitsadmin /transfer download https://github.com/msys2/msys2-installer/releases/download/2023-03-18/msys2-x86_64-20230318.exe %CD%\msys2-x86_64-20230318.exe
         cmd /c "msys2-x86_64-20230318.exe install --root C:\MSYS2 --confirm-command"
         ls C:\msys64\
         ls C:\msys64\usr\bin\
         ls C:\msys64\mingw64\bin\
         $ENV:Path="C:\msys64\mingw64\bin\;C:\msys64\usr\bin\;"+$ENV:Path
         $ENV:MSYSTEM="MINGW64"
         pacman -Syuu
         pacman -S --needed base-devel mingw-w64-x86_64-toolchain
         g++ -v
      - name: artifact upload
        uses: actions/upload-artifact@v3.0.0
        with:
          name: gcc-install
          path: /home/runner/work/gcc-build/gcc-build/install
          retention -days: 3
