name: C++
on: [push]
jobs:
  check-bats-version:
    runs-on: windows-latest
    steps:
      - name: artifact output
        run: |
         winget install MSYS2.MSYS2
         "C:/msys64/msys2_shell.cmd" -defterm -here -no-start -mingw64
         pacman -Suy
         pacman -Sy --needed base-devel mingw-w64-x86_64-toolchain
      - name: artifact upload
        uses: actions/upload-artifact@v3.0.0
        with:
          name: gcc-install
          path: /home/runner/work/gcc-build/gcc-build/install
          retention -days: 3
