name: C++
on: [push]
jobs:
  check-bats-version:
    runs-on: windows-latest
    steps:
      - name: artifact output
        run: |
         bitsadmin /transfer download https://github.com/msys2/msys2-installer/releases/download/2023-03-18/msys2-x86_64-20230318.exe %CD%\msys2-x86_64-20230318.exe
         cmd /c "msys2-x86_64-20230318.exe install --root C:\MSYS2 --confirm-command"
         ls C:\msys64\usr\
         ls C:\msys64\mingw64
         set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;C:\msys64\bin;%PATH%
         set MSYSTEM=MINGW64
         pacman -Syuu
         echo y > y
         cmd /c "pacman -S --needed base-devel mingw-w64-x86_64-toolchain < y"
         g++ -v
      - name: artifact upload
        uses: actions/upload-artifact@v3.0.0
        with:
          name: gcc-install
          path: /home/runner/work/gcc-build/gcc-build/install
          retention -days: 3
