name: C++
on: [push]
jobs:
  check-bats-version:
    runs-on: windows-latest
    steps:
      - name: artifact output
        run: |
         winget install MSYS2.MSYS2
         set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\local\bin;C:\msys64\usr\bin;C:\msys64\bin;%PATH%
         set MSYSTEM=MINGW64
         pacman -Syuu
         echo y > y
         cmd /c "pacman -S --needed base-devel mingw-w64-x86_64-toolchain < y"
         g++ -v
      - name: artifact upload
        uses: actions/upload-artifact@v3.0.0
        with:
          name: gcc-install
          path: /home/runner/work/gcc-build/gcc-build/install
          retention -days: 3
